### ISSUE TITLE
Picture Fix

### ISSUE THREAD

**Issue by gtf5022** [robthemonster/pear_bot#4]
const SEARCH_MODIFIERS = ['bartlett', 'anime', 'art', 'cute', 'animal crossing', 'bear'];

should be:

const SEARCH_MODIFIERS = ['bartlett', 'art', 'cute', 'animal crossing', 'ripe', 'fresh', 'shiny', 'perfect', 'moist', 'not weeb shit'];

**Comment by robthemonster** [comment]
dumb

**Comment by gtf5022** [comment]
Typical attitude of this developer.
